version: 1.1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    mkdir C:\projects\image-optimizer\IOptimizer\bin\Release\Tools >NUL

    copy C:\projects\image-optimizer\IOptimizer\Tools\*.*  C:\projects\image-optimizer\IOptimizer\bin\Release\Tools /Y >NUL

    nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a IOptimizer.zip -r %APPVEYOR_BUILD_FOLDER%\IOptimizer\bin\Release\

    appveyor PushArtifact IOptimizer.zip
deploy:
- provider: GitHub
  release: IOptimizer-v$(APPVEYOR_BUILD_VERSION)
  description: Release description
  auth_token:
    secure: 5ZaT9wKNoENOi2va55xzYo5MQyHlqRyQr71DFBw6A7ovfj0CBwa20gQrl13IjbqX
  artifact: /.*\.zip/
  on:
    branch: master
